### ISSUE TITLE
EC2インスタンスにqiita-stocker-backendが動作する環境を構築する

### ISSUE THREAD

**Issue by keitakn** [nekochans/nekochans#26]
# Doneの定義
- qiita-stocker-backendが動作するインスタンスが構築されている事

# 補足
おそらく以下の作業が必要になる。

- EC2インスタンスにLaravelが動作するミドルウェアをインストールする

PHP + nginx + php-fpmの環境を構築する。

- RDSクラスターを構築する
MySQL互換のAmazon Aurora Serverlessを選択すると料金的にお得なので良いかも🐱

EC2インスタンスはprivateネットワーク内にあるので、SSH用のサーバーから動作確認するなど、VPC内のサーバーから動作確認を行う必要がある。

ミドルウェアのインストール手順はQiita等にまとめてアウトプット出来るとベスト！

**Comment by keitakn** [comment]
@kobayashi-m42 参考になりそうな記事🐱

- https://qiita.com/kotarella1110/items/634f6fafeb33ae0f51dc
- https://qiita.com/yumatsud/items/7093fc9b389070ddecd1

**Comment by kobayashi-m42** [comment]
以下の手順で、AWSのインスタンスを作成。
[AWSのEC2にPHP + nginx + php-fpmの環境を構築する](https://qiita.com/kobayashi-m42/items/66db3b2da3b56f00ba47)
[Amazon Aurora Serverlessのインスタンスを作成し接続する](https://qiita.com/kobayashi-m42/items/cbb9686f2189a9097360)

EC2に、qiita-stocker-backendのソースコードをgit cloneし、APIの動作確認まで完了。
