### ISSUE TITLE
qiita-stocker-backendをALB経由で接続可能にする

### ISSUE THREAD

**Issue by keitakn** [nekochans/nekochans#27]
# Doneの定義
- qiita-stocker-backendがALB（Application Load Balancer）経由で作成されている事
- HTTPSで外部から接続可能になっている事
- インスタンスを2台にしてもアプリケーションが正常に動作している事が確認出来る事

# 補足
ALBのリスナーはHTTPSのみ許可する。

独自の証明書はこの時点では設定しなくてもOK🐱！

↓参考記事
https://qiita.com/keitakn/items/e19ef9f33249828fa94a

インスタンスを2台にしてみて、Webサーバーがちゃんと冗長化されている事が確認出来ればOK！

**Comment by kobayashi-m42** [comment]
ALBを作成し、ALB経由でQiitaStockerのAPIにアクセスできるか動作確認するところまで完了。
なお、このIssueでは、SSL証明書の設定は行わないためHTTPでの通信している。
