### ISSUE TITLE
作成したRDSClusterを任意の名前で接続出来るようにする

### ISSUE THREAD

**Issue by keitakn** [nekochans/nekochans#29]
# Doneの定義
- 作成したAmazon Aurora Clusterに任意のドメイン名で接続出来るようになっている事

# 補足
俗に言うローカルDNSを定義して上げれば良い。

こちらはグローバルドメインではないので好きな名前を付ければ良い（分かりやすい名前がベスト）

https://qiita.com/keitakn/items/4dbf03280868891f551b

（例）
qiita-stocker-db-writer.dev（開発環境用書き込みエンドポイント）
qiita-stocker-db-read.dev（開発環境用読み込みエンドポイント）

**Comment by kobayashi-m42** [comment]
## やったこと
- Route53でローカルDNSを作成
- DHCPオプションセット作成し、VPCにセットする
- qiita-stocker-backendの`.env`を修正し、RDSに接続できていることを確認
