### ISSUE TITLE
フロントエンドのデプロイ時にCloudFrontのCacheを自動で消す処理を追加する

### ISSUE THREAD

**Issue by keitakn** [nekochans/nekochans#34]
# Doneの定義
- 表題の件が実施されている事

# 補足
S3BucketにObjectがPUTされたタイミングでCloudFrontのCacheを消すLambda関数を作成する。

新しいGitRepositoryとして作成する必要がある。

出来ればリリースまでに欲しいが、最悪手動でも対応可能なので必須ではない。

**Comment by kobayashi-m42** [comment]
デプロイのタイミングでCacheを削除しているのでクローズ。
