### ISSUE TITLE
利用規約を作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/nekochans#39]
# Doneの定義
- 利用規約が作成されている事

**Comment by kobayashi-m42** [comment]
@keitakn  利用規約画面の作成のIssueとは別に、利用規約自体を作成するIssueを作成したよ！
ストーリーポイントは8かな🐱

**Comment by keitakn** [comment]
@kobayashi-m42 うん！8は必要そうだね🐱

**Comment by kobayashi-m42** [comment]
別途、slackでのレビューが完了したのでクローズする。
