### ISSUE TITLE
FargateのBlueGreenDeployを試してみる

### ISSUE THREAD

**Issue by keitakn** [nekochans/nekochans#53]
# Done
- デプロイ方法が記事にまとめられている事
- terraformの変更点が洗い出せている事

# 参考
https://aws.amazon.com/jp/blogs/news/use-aws-codedeploy-to-implement-blue-green-deployments-for-aws-fargate-and-amazon-ecs/

**Comment by kobayashi-m42** [comment]
デプロイ方法をQiitaの記事にまとめたので、クローズ。
